### ISSUE TITLE
export redmine.client

### ISSUE THREAD

**Issue by robvdl** [mattn/go-redmine#22]
I need to use it and it isn't exported, can we please export this as Client please.

**Comment by mattn** [comment]
Why not use NewClient?

**Comment by robvdl** [comment]
Please note my comment for this I accidentally put on the wrong ticket #1 

Basically I am already calling NewClient, but I want to be able to pass the result from this to another function in my own code, but this is not possible if redmine.client is not exported.  It is easily fixed by making redmine.Client exported.
