### ISSUE TITLE
Lack of filtering options when fetching issues for example

### ISSUE THREAD

**Issue by robvdl** [mattn/go-redmine#23]
I need to fetch issues but apply some filters, for example status_id=* to get all stories including closed ones.

I was looking at the Issues() function and it doesn't really provide ways to pass in extra query params for filtering, which is sorely needed or I have to fetch everyting... a page at a time and filter over the results in Go.

I need this for a project now, so going to implement it all in a fork and see how it turns out.

**Comment by mattn** [comment]
Did you try IssuesByFilter ?

**Comment by robvdl** [comment]
I see that now sorry.

**Comment by mattn** [comment]
NP
