### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by zztkm** [mattn/go-redmine#54]
I am currently unable to find the documentation for mattn/go-redmine at [pkg.go.dev](https://pkg.go.dev/github.com/mattn/go-redmine@v0.0.3).
This seems to be due to the fact that the repository does not contain the license file.

Perhaps if you could add the license file, we will be able to check the package documentation on the web.

It would be great if you could support this.

refs:
- https://pkg.go.dev/license-policy

**Comment by mattn** [comment]
added. thank you
